### ISSUE TITLE
为什么我这里最新版不让用wl指令（）

### ISSUE THREAD

**Issue by yiqv** [ApliNi/IpacWhitelist#24]

**Comment by yiqv** [comment]
[21:06:05 WARN]: Unexpected exception while parsing console command "wl"
org.bukkit.command.CommandException: Cannot execute command 'wl' in plugin IpacWhitelist v4.1.1-rc5 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:985) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[paper-1.21.jar:1.21-107-aa36ae6]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]

**Comment by yiqv** [comment]
服务器控制台输入会提示这个

**Comment by yiqv** [comment]
好怪

**Comment by ApliNi** [comment]
我认为你需要提供完整日志, 需要知道为什么插件被禁用才能解决问题
